apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piggymetrics
  template:
    metadata:
      labels:
        app: piggymetrics
    spec:
      containers:
      - name: registry
        image: sqshq/piggymetrics-registry
        ports:
         - containerPort: 8761
        env:
          - name : CONFIG_SERVICE_PASSWORD
            value: CONFIG_SERVICE_PASSWORD
        resources:
           requests:
              memory: "64Mi"
              cpu: "250m"
           limits:
              memory: "128Mi"
              cpu: "500m"
