apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piggymetrics
  template:
    metadata:
      labels:
        app: piggymetrics
    spec:
      containers:
      - name: auth-service
        image: sqshq/piggymetrics-auth-service
        env:
          - name : CONFIG_SERVICE_PASSWORD
            value: CONFIG_SERVICE_PASSWORD
          - name : NOTIFICATION_SERVICE_PASSWORD
            value: NOTIFICATION_SERVICE_PASSWORD
          - name : STATISTICS_SERVICE_PASSWORD
            value: STATISTICS_SERVICE_PASSWORD
          - name : ACCOUNT_SERVICE_PASSWORD
            value: ACCOUNT_SERVICE_PASSWORD
          - name : MONGODB_PASSWORD
            value: MONGODB_PASSWORD
        resources:
           requests:
              memory: "64Mi"
              cpu: "250m"
           limits:
              memory: "128Mi"
              cpu: "500m"
