apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piggymetrics
  template:
    metadata:
      labels:
        app: piggymetrics
    spec:
      containers:
      - name: account-service
        image: sqshq/piggymetrics-account-service
        resources:
           requests:
              memory: "64Mi"
              cpu: "250m"
           limits:
              memory: "128Mi"
              cpu: "500m"
