apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piggymetrics
  template:
    metadata:
      labels:
        app: piggymetrics
    spec:
      containers:
      - name: mongodb
        image: sqshq/piggymetrics-mongodb
        ports:
         - containerPort: 4000
        env:
          - name : MONGODB_PASSWORD
            value: MONGODB_PASSWORD
          - name : INIT_DUMP
            value : account-service-dump.js
        resources:
           requests:
              memory: "64Mi"
              cpu: "250m"
           limits:
              memory: "128Mi"
              cpu: "500m"
